const HTML_FOR_WORK_EXPERIENCE_1 = '01-work-experience-history';
const HTML_FOR_WORK_EXPERIENCE_2 = '02-work-experience-history';
const HTML_FOR_WORK_EXPERIENCE_3 = '03-work-experience-history';


const HTML_FOR_CURRENT_SPECIALIZATION = '01-about-me-cs';
const HTML_FOR_DEVELOPMENT_ENVIRONMENT = '02-about-me-de';
const HTML_FOR_ACTIVE_PRACTICAL_APPROACH = '03-about-me-apa';
const HTML_FOR_MAIN_CONCEPTS = '04-about-me-mc';


const HTML_FOR_MY_SOCIAL_GOALS_THROUGH_MAIN = '01-my-social-goals-through-main';
const HTML_FOR_MY_SOCIAL_GOALS_THROUGH_SECONDARY = '02-my-social-goals-through-secondary';

const HTML_FOR_MY_PERSONAL_GOALS_THROUGH_MAIN = '01-my-personal-goals-through-main';
const HTML_FOR_MY_PERSONAL_GOALS_THROUGH_SECONDARY = '02-my-personal-goals-through-secondary';

export {
    HTML_FOR_WORK_EXPERIENCE_1,
    HTML_FOR_WORK_EXPERIENCE_2,
    HTML_FOR_WORK_EXPERIENCE_3,
    HTML_FOR_CURRENT_SPECIALIZATION,
    HTML_FOR_DEVELOPMENT_ENVIRONMENT,
    HTML_FOR_ACTIVE_PRACTICAL_APPROACH,
    HTML_FOR_MAIN_CONCEPTS,
    HTML_FOR_MY_SOCIAL_GOALS_THROUGH_MAIN,
    HTML_FOR_MY_SOCIAL_GOALS_THROUGH_SECONDARY,
    HTML_FOR_MY_PERSONAL_GOALS_THROUGH_MAIN,
    HTML_FOR_MY_PERSONAL_GOALS_THROUGH_SECONDARY
};
