const PIXEL_ART_ANIME_UMI = 'anime-umi';
const PIXEL_ART_ANIME_RINTARO = 'anime-rintaro';
const PIXEL_ART_ANIME_TODOROKI = 'anime-todoroki';
const PIXEL_ART_ANIME_HINATA = 'anime-hinata';
const PIXEL_ART_ANIME_KURISU = 'anime-kurisu';
const PIXEL_ART_ANIME_KANAO = 'anime-kanao';
const PIXEL_ART_ANIME_KOMI = 'anime-komi';

const PIXEL_ART_ANIME_ITSUKI_NAKANO_CARD = 'anime-itsuki-nakano-card';
const PIXEL_ART_ANIME_MIKU_NAKANO_CARD = 'anime-miku-nakano-card';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO_CARD = 'anime-yotsuba-nakano-card';
const PIXEL_ART_ANIME_NINO_NAKANO_CARD = 'anime-nino-nakano-card';
const PIXEL_ART_ANIME_ICHIKA_NAKANO_CARD = 'anime-ichika-nakano-card';

const PIXEL_ART_ANIME_ITSUKI_NAKANO = 'anime-itsuki-nakano';
const PIXEL_ART_ANIME_MIKU_NAKANO = 'anime-miku-nakano';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO = 'anime-yotsuba-nakano';
const PIXEL_ART_ANIME_NINO_NAKANO = 'anime-nino-nakano';
const PIXEL_ART_ANIME_ICHIKA_NAKANO = 'anime-ichika-nakano';

const PIXEL_ART_ANIME_MINICODE_ANIMATION_V1 = 'anime-minicode-animation-v1';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V2 = 'anime-minicode-animation-v2';


const PIXEL_ART_ITEM_DESK = 'item-desk';
const PIXEL_ART_ITEM_WHITEBOARD = 'item-whiteboard';
const PIXEL_ART_ITEM_COMPUTERS_STEINS_GATE = 'item-computers-steins-gate';
const PIXEL_ART_ITEM_MICROWAVE_STEINS_GATE = 'item-microwave-steins-gate';
const PIXEL_ART_ITEM_STICKY_NOTE_SINGLE = 'item-sticky-note-single';
const PIXEL_ART_ITEM_STICKY_NOTE_GROUP = 'item-sticky-note-group';
const PIXEL_ART_ITEM_BOOK = 'item-book';
const PIXEL_ART_ITEM_BOOKS = 'item-books';
const PIXEL_ART_ITEM_DIALOG = 'item-dialog';

export {
    PIXEL_ART_ANIME_UMI,
    PIXEL_ART_ANIME_RINTARO,
    PIXEL_ART_ANIME_TODOROKI,
    PIXEL_ART_ANIME_HINATA,
    PIXEL_ART_ANIME_KURISU,
    PIXEL_ART_ANIME_KANAO,
    PIXEL_ART_ANIME_KOMI,

    PIXEL_ART_ANIME_ITSUKI_NAKANO_CARD,
    PIXEL_ART_ANIME_MIKU_NAKANO_CARD,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO_CARD,
    PIXEL_ART_ANIME_ICHIKA_NAKANO_CARD,
    PIXEL_ART_ANIME_NINO_NAKANO_CARD,

    PIXEL_ART_ANIME_ITSUKI_NAKANO,
    PIXEL_ART_ANIME_MIKU_NAKANO,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO,
    PIXEL_ART_ANIME_NINO_NAKANO,
    PIXEL_ART_ANIME_ICHIKA_NAKANO,

    PIXEL_ART_ANIME_MINICODE_ANIMATION_V1,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V2,

    PIXEL_ART_ITEM_DESK,
    PIXEL_ART_ITEM_WHITEBOARD,
    PIXEL_ART_ITEM_COMPUTERS_STEINS_GATE,
    PIXEL_ART_ITEM_MICROWAVE_STEINS_GATE,
    PIXEL_ART_ITEM_STICKY_NOTE_SINGLE,
    PIXEL_ART_ITEM_STICKY_NOTE_GROUP,
    PIXEL_ART_ITEM_BOOK,
    PIXEL_ART_ITEM_BOOKS,
    PIXEL_ART_ITEM_DIALOG
};
