const PIXEL_ART_ITEM_ANIME_DANGO_BLUE = 'item-anime-dango-blue';
const PIXEL_ART_ITEM_ANIME_DANGO_PINK = 'item-anime-dango-pink';
const PIXEL_ART_ITEM_ANIME_DANGO_YELLOW = 'item-anime-dango-yellow';

const PIXEL_ART_ITEM_ANIME_HITAI_ATE = 'item-anime-hitai-ate';
const PIXEL_ART_ITEM_ANIME_PARCHMENT = 'item-anime-parchment';

const PIXEL_ART_ITEM_ANIME_STEINS_GATE_COMPUTERS = 'item-anime-steins-gate-computers';
const PIXEL_ART_ITEM_ANIME_STEINS_GATE_MICROWAVE = 'item-anime-steins-gate-microwave';

const PIXEL_ART_ITEM_ARCADE = 'item-arcade';

const PIXEL_ART_ITEM_BOOK_UNIVERSITY = 'item-book-university';
const PIXEL_ART_ITEM_BOOK = 'item-book';
const PIXEL_ART_ITEM_BOOKS = 'item-books';

const PIXEL_ART_ITEM_CUP_COFFEE_ANIMATION = 'item-cup-coffee-animation';

const PIXEL_ART_ITEM_DESK_ANIMATION = 'item-desk-animation';
const PIXEL_ART_ITEM_DESK_INVERT_ANIMATION = 'item-desk-invert-animation';

const PIXEL_ART_ITEM_DOMO_ANIMATION = 'item-domo-animation';
const PIXEL_ART_ITEM_DOMO = 'item-domo';

const PIXEL_ART_ITEM_HOURGLASS = 'item-hourglass';

const PIXEL_ART_ITEM_LAMP = 'item-lamp';

const PIXEL_ART_ITEM_MORTARBOARD = 'item-mortarboard';

const PIXEL_ART_ITEM_PENCIL_BLUE = 'item-pencil-blue';
const PIXEL_ART_ITEM_PENCIL_PINK = 'item-pencil-pink';
const PIXEL_ART_ITEM_PENCIL_RED = 'item-pencil-red';
const PIXEL_ART_ITEM_PENCIL_YELLOW = 'item-pencil-yellow';

const PIXEL_ART_ITEM_PUMP_GAME_LOGO = 'item-pump-game-logo';
const PIXEL_ART_ITEM_PUMP_STEP_BLUE_ANIMATION = 'item-pump-step-blue-animation';
const PIXEL_ART_ITEM_PUMP_STEP_BLUE = 'item-pump-step-blue';
const PIXEL_ART_ITEM_PUMP_STEP_CENTER_ANIMATION = 'item-pump-step-center-animation';
const PIXEL_ART_ITEM_PUMP_STEP_CENTER = 'item-pump-step-center';
const PIXEL_ART_ITEM_PUMP_STEP_RED_ANIMATION = 'item-pump-step-red-animation';
const PIXEL_ART_ITEM_PUMP_STEP_RED = 'item-pump-step-red';

const PIXEL_ART_ITEM_SOCCER_BALL = 'item-soccer-ball';

const PIXEL_ART_ITEM_STICKY_NOTE_GROUP = 'item-sticky-note-group';
const PIXEL_ART_ITEM_STICKY_NOTE = 'item-sticky-note';

const PIXEL_ART_ITEM_WHITEBOARD = 'item-whiteboard';



















const PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT_V2 = 'item-speech-bubble-bit-v2';

const PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT = 'item-speech-bubble-bit';





















const PIXEL_ART_ANIME_UMI = 'anime-umi';
const PIXEL_ART_ANIME_RINTARO = 'anime-rintaro';
const PIXEL_ART_ANIME_TODOROKI = 'anime-todoroki';
const PIXEL_ART_ANIME_HINATA = 'anime-hinata';
const PIXEL_ART_ANIME_KURISU = 'anime-kurisu';
const PIXEL_ART_ANIME_KANAO = 'anime-kanao';
const PIXEL_ART_ANIME_KOMI = 'anime-komi';

const PIXEL_ART_ADVENTURE_TIME_JAKE_THE_DOG = 'anime-jake-the-dog';
const PIXEL_ART_ADVENTURE_TIME_BMO = 'anime-bmo';

const PIXEL_ART_ANIME_ITSUKI_NAKANO_CARD = 'anime-itsuki-nakano-card';
const PIXEL_ART_ANIME_MIKU_NAKANO_CARD = 'anime-miku-nakano-card';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO_CARD = 'anime-yotsuba-nakano-card';
const PIXEL_ART_ANIME_NINO_NAKANO_CARD = 'anime-nino-nakano-card';
const PIXEL_ART_ANIME_ICHIKA_NAKANO_CARD = 'anime-ichika-nakano-card';

const PIXEL_ART_ANIME_ITSUKI_NAKANO = 'anime-itsuki-nakano';
const PIXEL_ART_ANIME_MIKU_NAKANO = 'anime-miku-nakano';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO = 'anime-yotsuba-nakano';
const PIXEL_ART_ANIME_NINO_NAKANO = 'anime-nino-nakano';
const PIXEL_ART_ANIME_ICHIKA_NAKANO = 'anime-ichika-nakano';

const PIXEL_ART_ANIME_ITSUKI_NAKANO_ANIMATION = 'anime-itsuki-nakano-animation';
const PIXEL_ART_ANIME_MIKU_NAKANO_ANIMATION = 'anime-miku-nakano-animation';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO_ANIMATION = 'anime-yotsuba-nakano-animation';
const PIXEL_ART_ANIME_NINO_NAKANO_ANIMATION = 'anime-nino-nakano-animation';
const PIXEL_ART_ANIME_ICHIKA_NAKANO_ANIMATION = 'anime-ichika-nakano-animation';

const PIXEL_ART_ANIME_MINICODE_ANIMATION_V1 = 'anime-minicode-animation-v1';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V2 = 'anime-minicode-animation-v2';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V3 = 'anime-minicode-animation-v3';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V4 = 'anime-minicode-animation-v4';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V5 = 'anime-minicode-animation-v5';

const PIXEL_ART_ANIME_MINICODE_BASIC_V1 = 'anime-minicode-basic-v1';
const PIXEL_ART_ANIME_MINICODE_BASIC_V2 = 'anime-minicode-basic-v2';















export {
    PIXEL_ART_ITEM_ARCADE,
    PIXEL_ART_ITEM_PUMP_STEP_BLUE,
    PIXEL_ART_ITEM_PUMP_STEP_RED,
    PIXEL_ART_ITEM_PUMP_STEP_CENTER,












    PIXEL_ART_ANIME_UMI,
    PIXEL_ART_ANIME_RINTARO,
    PIXEL_ART_ANIME_TODOROKI,
    PIXEL_ART_ANIME_HINATA,
    PIXEL_ART_ANIME_KURISU,
    PIXEL_ART_ANIME_KANAO,
    PIXEL_ART_ANIME_KOMI,

    PIXEL_ART_ANIME_ITSUKI_NAKANO_CARD,
    PIXEL_ART_ANIME_MIKU_NAKANO_CARD,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO_CARD,
    PIXEL_ART_ANIME_ICHIKA_NAKANO_CARD,
    PIXEL_ART_ANIME_NINO_NAKANO_CARD,

    PIXEL_ART_ANIME_ITSUKI_NAKANO,
    PIXEL_ART_ANIME_MIKU_NAKANO,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO,
    PIXEL_ART_ANIME_NINO_NAKANO,
    PIXEL_ART_ANIME_ICHIKA_NAKANO,

    PIXEL_ART_ANIME_ITSUKI_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_MIKU_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_NINO_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_ICHIKA_NAKANO_ANIMATION,

    PIXEL_ART_ANIME_MINICODE_ANIMATION_V1,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V2,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V3,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V4,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V5,

    PIXEL_ART_ANIME_MINICODE_BASIC_V1,
    PIXEL_ART_ANIME_MINICODE_BASIC_V2,

    PIXEL_ART_ITEM_DESK_ANIMATION,
    PIXEL_ART_ITEM_DESK_INVERT_ANIMATION,
    PIXEL_ART_ITEM_WHITEBOARD,
    PIXEL_ART_ITEM_ANIME_STEINS_GATE_COMPUTERS,
    PIXEL_ART_ITEM_ANIME_STEINS_GATE_MICROWAVE,
    PIXEL_ART_ITEM_STICKY_NOTE,
    PIXEL_ART_ITEM_STICKY_NOTE_GROUP,
    PIXEL_ART_ITEM_BOOK,
    PIXEL_ART_ITEM_BOOKS,
    PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT,
    PIXEL_ART_ITEM_ANIME_HITAI_ATE,
    PIXEL_ART_ITEM_ANIME_PARCHMENT,
    PIXEL_ART_ITEM_MORTARBOARD,
    PIXEL_ART_ITEM_BOOK_UNIVERSITY,
    PIXEL_ART_ITEM_HOURGLASS,
    PIXEL_ART_ITEM_LAMP,
    PIXEL_ART_ITEM_CUP_COFFEE_ANIMATION,
    PIXEL_ART_ITEM_PENCIL_BLUE,
    PIXEL_ART_ITEM_PENCIL_RED,
    PIXEL_ART_ITEM_PENCIL_YELLOW,
    PIXEL_ART_ITEM_PENCIL_PINK,
    PIXEL_ART_ITEM_SOCCER_BALL,
    PIXEL_ART_ITEM_DOMO,
    PIXEL_ART_ITEM_DOMO_ANIMATION,
    PIXEL_ART_ITEM_PUMP_GAME_LOGO,
    PIXEL_ART_ITEM_PUMP_STEP_BLUE_ANIMATION,
    PIXEL_ART_ITEM_PUMP_STEP_RED_ANIMATION,
    PIXEL_ART_ITEM_PUMP_STEP_CENTER_ANIMATION,
    PIXEL_ART_ADVENTURE_TIME_JAKE_THE_DOG,
    PIXEL_ART_ADVENTURE_TIME_BMO,
    PIXEL_ART_ITEM_ANIME_DANGO_BLUE,
    PIXEL_ART_ITEM_ANIME_DANGO_PINK,
    PIXEL_ART_ITEM_ANIME_DANGO_YELLOW,
    PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT_V2
};
