const PIXEL_ART_ANIME_UMI = 'anime-umi';
const PIXEL_ART_ANIME_RINTARO = 'anime-rintaro';
const PIXEL_ART_ANIME_TODOROKI = 'anime-todoroki';
const PIXEL_ART_ANIME_HINATA = 'anime-hinata';
const PIXEL_ART_ANIME_KURISU = 'anime-kurisu';
const PIXEL_ART_ANIME_KANAO = 'anime-kanao';
const PIXEL_ART_ANIME_KOMI = 'anime-komi';




const PIXEL_ART_ADVENTURE_TIME_JAKE_THE_DOG = 'anime-jake-the-dog';
const PIXEL_ART_ADVENTURE_TIME_BMO = 'anime-bmo';





const PIXEL_ART_ANIME_ITSUKI_NAKANO_CARD = 'anime-itsuki-nakano-card';
const PIXEL_ART_ANIME_MIKU_NAKANO_CARD = 'anime-miku-nakano-card';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO_CARD = 'anime-yotsuba-nakano-card';
const PIXEL_ART_ANIME_NINO_NAKANO_CARD = 'anime-nino-nakano-card';
const PIXEL_ART_ANIME_ICHIKA_NAKANO_CARD = 'anime-ichika-nakano-card';

const PIXEL_ART_ANIME_ITSUKI_NAKANO = 'anime-itsuki-nakano';
const PIXEL_ART_ANIME_MIKU_NAKANO = 'anime-miku-nakano';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO = 'anime-yotsuba-nakano';
const PIXEL_ART_ANIME_NINO_NAKANO = 'anime-nino-nakano';
const PIXEL_ART_ANIME_ICHIKA_NAKANO = 'anime-ichika-nakano';

const PIXEL_ART_ANIME_ITSUKI_NAKANO_ANIMATION = 'anime-itsuki-nakano-animation';
const PIXEL_ART_ANIME_MIKU_NAKANO_ANIMATION = 'anime-miku-nakano-animation';
const PIXEL_ART_ANIME_YOTSUBA_NAKANO_ANIMATION = 'anime-yotsuba-nakano-animation';
const PIXEL_ART_ANIME_NINO_NAKANO_ANIMATION = 'anime-nino-nakano-animation';
const PIXEL_ART_ANIME_ICHIKA_NAKANO_ANIMATION = 'anime-ichika-nakano-animation';

const PIXEL_ART_ANIME_MINICODE_ANIMATION_V1 = 'anime-minicode-animation-v1';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V2 = 'anime-minicode-animation-v2';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V3 = 'anime-minicode-animation-v3';
const PIXEL_ART_ANIME_MINICODE_ANIMATION_V4 = 'anime-minicode-animation-v4';

const PIXEL_ART_ITEM_DESK = 'item-desk';
const PIXEL_ART_ITEM_WHITEBOARD = 'item-whiteboard';
const PIXEL_ART_ITEM_COMPUTERS_STEINS_GATE = 'item-computers-steins-gate';
const PIXEL_ART_ITEM_MICROWAVE_STEINS_GATE = 'item-microwave-steins-gate';
const PIXEL_ART_ITEM_STICKY_NOTE_SINGLE = 'item-sticky-note-single';
const PIXEL_ART_ITEM_STICKY_NOTE_GROUP = 'item-sticky-note-group';
const PIXEL_ART_ITEM_BOOK = 'item-book';
const PIXEL_ART_ITEM_BOOKS = 'item-books';
const PIXEL_ART_ITEM_DIALOG_VERTICAL = 'item-dialog-vertical';
const PIXEL_ART_ITEM_HITAI_ATE = 'item-hitai-ate';
const PIXEL_ART_ITEM_PARCHMENT = 'item-parchment';
const PIXEL_ART_ITEM_SEALED_PARCHMENT = 'item-sealed-parchment';
const PIXEL_ART_ITEM_BLUE_STEP = 'item-blue-step';
const PIXEL_ART_ITEM_RED_STEP = 'item-red-step';
const PIXEL_ART_ITEM_CENTER_STEP = 'item-center-step';
const PIXEL_ART_ITEM_MORTARBOARD = 'item-mortarboard';
const PIXEL_ART_ITEM_BOOK_UNIVERSITY = 'item-book-university';
const PIXEL_ART_ITEM_HOURGLASS = 'item-hourglass';
const PIXEL_ART_ITEM_DESK_LAMP = 'item-desk-lamp';
const PIXEL_ART_ITEM_CUP_COFFEE = 'item-cup-coffee';
const PIXEL_ART_ITEM_PENCIL_BLUE = 'item-pencil-blue';
const PIXEL_ART_ITEM_PENCIL_RED = 'item-pencil-red';
const PIXEL_ART_ITEM_PENCIL_YELLOW = 'item-pencil-yellow';
const PIXEL_ART_ITEM_PENCIL_PINK = 'item-pencil-pink';
const PIXEL_ART_ITEM_ARCADE = 'item-arcade';
const PIXEL_ART_ITEM_SOCCER = 'item-soccer';
const PIXEL_ART_ITEM_DOMO = 'item-domo';
const PIXEL_ART_ITEM_DOMO_ANIMATION = 'item-domo-animation';
const PIXEL_ART_ITEM_PUMP_GAME = 'item-pump-game';
const PIXEL_ART_ITEM_PUMP_GAME_BLUE_STEP = 'item-pump-game-blue-step';
const PIXEL_ART_ITEM_PUMP_GAME_RED_STEP = 'item-pump-game-red-step';
const PIXEL_ART_ITEM_PUMP_GAME_CENTER_STEP = 'item-pump-game-center-step';
const PIXEL_ART_ITEM_DANGO_BLUE = 'item-dango-blue';
const PIXEL_ART_ITEM_DANGO_PINK = 'item-dango-pink';
const PIXEL_ART_ITEM_DANGO_YELLOW = 'item-dango-yellow';


export {
    PIXEL_ART_ANIME_UMI,
    PIXEL_ART_ANIME_RINTARO,
    PIXEL_ART_ANIME_TODOROKI,
    PIXEL_ART_ANIME_HINATA,
    PIXEL_ART_ANIME_KURISU,
    PIXEL_ART_ANIME_KANAO,
    PIXEL_ART_ANIME_KOMI,

    PIXEL_ART_ANIME_ITSUKI_NAKANO_CARD,
    PIXEL_ART_ANIME_MIKU_NAKANO_CARD,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO_CARD,
    PIXEL_ART_ANIME_ICHIKA_NAKANO_CARD,
    PIXEL_ART_ANIME_NINO_NAKANO_CARD,

    PIXEL_ART_ANIME_ITSUKI_NAKANO,
    PIXEL_ART_ANIME_MIKU_NAKANO,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO,
    PIXEL_ART_ANIME_NINO_NAKANO,
    PIXEL_ART_ANIME_ICHIKA_NAKANO,

    PIXEL_ART_ANIME_ITSUKI_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_MIKU_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_YOTSUBA_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_NINO_NAKANO_ANIMATION,
    PIXEL_ART_ANIME_ICHIKA_NAKANO_ANIMATION,

    PIXEL_ART_ANIME_MINICODE_ANIMATION_V1,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V2,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V3,
    PIXEL_ART_ANIME_MINICODE_ANIMATION_V4,

    PIXEL_ART_ITEM_DESK,
    PIXEL_ART_ITEM_WHITEBOARD,
    PIXEL_ART_ITEM_COMPUTERS_STEINS_GATE,
    PIXEL_ART_ITEM_MICROWAVE_STEINS_GATE,
    PIXEL_ART_ITEM_STICKY_NOTE_SINGLE,
    PIXEL_ART_ITEM_STICKY_NOTE_GROUP,
    PIXEL_ART_ITEM_BOOK,
    PIXEL_ART_ITEM_BOOKS,
    PIXEL_ART_ITEM_DIALOG_VERTICAL,
    PIXEL_ART_ITEM_HITAI_ATE,
    PIXEL_ART_ITEM_PARCHMENT,
    PIXEL_ART_ITEM_SEALED_PARCHMENT,
    PIXEL_ART_ITEM_BLUE_STEP,
    PIXEL_ART_ITEM_RED_STEP,
    PIXEL_ART_ITEM_CENTER_STEP,
    PIXEL_ART_ITEM_MORTARBOARD,
    PIXEL_ART_ITEM_BOOK_UNIVERSITY,
    PIXEL_ART_ITEM_HOURGLASS,
    PIXEL_ART_ITEM_DESK_LAMP,
    PIXEL_ART_ITEM_CUP_COFFEE,
    PIXEL_ART_ITEM_PENCIL_BLUE,
    PIXEL_ART_ITEM_PENCIL_RED,
    PIXEL_ART_ITEM_PENCIL_YELLOW,
    PIXEL_ART_ITEM_PENCIL_PINK,
    PIXEL_ART_ITEM_ARCADE,
    PIXEL_ART_ITEM_SOCCER,
    PIXEL_ART_ITEM_DOMO,
    PIXEL_ART_ITEM_DOMO_ANIMATION,
    PIXEL_ART_ITEM_PUMP_GAME,
    PIXEL_ART_ITEM_PUMP_GAME_BLUE_STEP,
    PIXEL_ART_ITEM_PUMP_GAME_RED_STEP,
    PIXEL_ART_ITEM_PUMP_GAME_CENTER_STEP,
    PIXEL_ART_ADVENTURE_TIME_JAKE_THE_DOG,
    PIXEL_ART_ADVENTURE_TIME_BMO,
    PIXEL_ART_ITEM_DANGO_BLUE,
    PIXEL_ART_ITEM_DANGO_PINK,
    PIXEL_ART_ITEM_DANGO_YELLOW
};
