const PIXEL_ART_ITEM_ANIME_DANGO_BLUE = 'item-anime-dango-blue';
const PIXEL_ART_ITEM_ANIME_DANGO_PINK = 'item-anime-dango-pink';
const PIXEL_ART_ITEM_ANIME_DANGO_YELLOW = 'item-anime-dango-yellow';

const PIXEL_ART_ITEM_ANIME_HITAI_ATE = 'item-anime-hitai-ate';
const PIXEL_ART_ITEM_ANIME_PARCHMENT = 'item-anime-parchment';

const PIXEL_ART_ITEM_ANIME_STEINS_GATE_COMPUTERS = 'item-anime-steins-gate-computers';
const PIXEL_ART_ITEM_ANIME_STEINS_GATE_MICROWAVE = 'item-anime-steins-gate-microwave';

const PIXEL_ART_ITEM_ARCADE = 'item-arcade';

const PIXEL_ART_ITEM_BOOK_UNIVERSITY = 'item-book-university';
const PIXEL_ART_ITEM_BOOK = 'item-book';
const PIXEL_ART_ITEM_BOOKS = 'item-books';

const PIXEL_ART_ITEM_CUP_COFFEE_ANIMATION = 'item-cup-coffee-animation';

const PIXEL_ART_ITEM_DESK_ANIMATION = 'item-desk-animation';
const PIXEL_ART_ITEM_DESK_INVERT_ANIMATION = 'item-desk-invert-animation';

const PIXEL_ART_ITEM_DOMO_ANIMATION = 'item-domo-animation';
const PIXEL_ART_ITEM_DOMO = 'item-domo';

const PIXEL_ART_ITEM_HOURGLASS = 'item-hourglass';

const PIXEL_ART_ITEM_LAMP = 'item-lamp';

const PIXEL_ART_ITEM_MORTARBOARD = 'item-mortarboard';

const PIXEL_ART_ITEM_PENCIL_BLUE = 'item-pencil-blue';
const PIXEL_ART_ITEM_PENCIL_PINK = 'item-pencil-pink';
const PIXEL_ART_ITEM_PENCIL_RED = 'item-pencil-red';
const PIXEL_ART_ITEM_PENCIL_YELLOW = 'item-pencil-yellow';

const PIXEL_ART_ITEM_PUMP_GAME_LOGO = 'item-pump-game-logo';
const PIXEL_ART_ITEM_PUMP_STEP_BLUE_ANIMATION = 'item-pump-step-blue-animation';
const PIXEL_ART_ITEM_PUMP_STEP_BLUE = 'item-pump-step-blue';
const PIXEL_ART_ITEM_PUMP_STEP_CENTER_ANIMATION = 'item-pump-step-center-animation';
const PIXEL_ART_ITEM_PUMP_STEP_CENTER = 'item-pump-step-center';
const PIXEL_ART_ITEM_PUMP_STEP_RED_ANIMATION = 'item-pump-step-red-animation';
const PIXEL_ART_ITEM_PUMP_STEP_RED = 'item-pump-step-red';

const PIXEL_ART_ITEM_SOCCER_BALL = 'item-soccer-ball';

const PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT_V2 = 'item-speech-bubble-bit-v2';
const PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT = 'item-speech-bubble-bit';

const PIXEL_ART_ITEM_STICKY_NOTE_GROUP = 'item-sticky-note-group';
const PIXEL_ART_ITEM_STICKY_NOTE = 'item-sticky-note';

const PIXEL_ART_ITEM_WHITEBOARD = 'item-whiteboard';


/* ******************************************************* */


const PIXEL_ART_ANIME_ADVENTURE_TIME_BMO_ANIMATION = 'anime-adventure-time-bmo-animation';
const PIXEL_ART_ANIME_ADVENTURE_TIME_FINN_THE_HUMAN_ANIMATION = 'anime-adventure-time-finn-the-human-animation';
const PIXEL_ART_ANIME_ADVENTURE_TIME_JAKE_THE_DOG_ANIMATION = 'anime-adventure-time-jake-the-dog-animation';
const PIXEL_ART_ANIME_ADVENTURE_TIME_MARCELINE_ANIMATION = 'anime-adventure-time-marceline-animation';

const PIXEL_ART_ANIME_BOKU_NO_HERO_TODOROKI_ANIMATION = 'anime-boku-no-hero-todoroki-animation';
const PIXEL_ART_ANIME_KIMETSU_NO_YAIBA_KANAO = 'anime-kimetsu-no-yaiba-kanao';
const PIXEL_ART_ANIME_KOMI_SAN_WA_KOMYUSHOU_DESU_KOMI = 'anime-komi-san-wa-komyushou-desu-komi';

const PIXEL_ART_ANIME_MINIDEV_V1_ANIMATION = 'anime-minidev-v1-animation';
const PIXEL_ART_ANIME_MINIDEV_V2_ANIMATION = 'anime-minidev-v2-animation';
const PIXEL_ART_ANIME_MINIDEV_V3_ANIMATION = 'anime-minidev-v3-animation';
const PIXEL_ART_ANIME_MINIDEV_V4_ANIMATION = 'anime-minidev-v4-animation';
const PIXEL_ART_ANIME_MINIDEV_V5_ANIMATION = 'anime-minidev-v5-animation';

const PIXEL_ART_ANIME_NAKANO_ICHIKA_ANIMATION = 'anime-nakano-ichika-animation';
const PIXEL_ART_ANIME_NAKANO_ICHIKA_CARD_ANIMATION = 'anime-nakano-ichika-card-animation';
const PIXEL_ART_ANIME_NAKANO_ITSUKI_ANIMATION = 'anime-nakano-itsuki-animation';
const PIXEL_ART_ANIME_NAKANO_ITSUKI_CARD_ANIMATION = 'anime-nakano-itsuki-card-animation';
const PIXEL_ART_ANIME_NAKANO_MIKU_ANIMATION = 'anime-nakano-miku-animation';
const PIXEL_ART_ANIME_NAKANO_MIKU_CARD_ANIMATION = 'anime-nakano-miku-card-animation';
const PIXEL_ART_ANIME_NAKANO_NINO_ANIMATION = 'anime-nakano-nino-animation';
const PIXEL_ART_ANIME_NAKANO_NINO_CARD_ANIMATION = 'anime-nakano-nino-card-animation';
const PIXEL_ART_ANIME_NAKANO_YOTSUBA_ANIMATION = 'anime-nakano-yotsuba-animation';
const PIXEL_ART_ANIME_NAKANO_YOTSUBA_CARD_ANIMATION = 'anime-nakano-yotsuba-card-animation';

const PIXEL_ART_ANIME_NARUTO_HINATA_ANIMATION = 'anime-naruto-hinata-animation';

const PIXEL_ART_ANIME_STEINS_GATE_KURISU_ANIMATION = 'anime-steins-gate-kurisu-animation';
const PIXEL_ART_ANIME_STEINS_GATE_RINTARO_ANIMATION = 'anime-steins-gate-rintaro-animation';

const PIXEL_ART_ANIME_UMI_ANIMATION = 'anime-umi-animation';


export {
    PIXEL_ART_ITEM_ANIME_DANGO_BLUE,
    PIXEL_ART_ITEM_ANIME_DANGO_PINK,
    PIXEL_ART_ITEM_ANIME_DANGO_YELLOW,
    PIXEL_ART_ITEM_ANIME_HITAI_ATE,
    PIXEL_ART_ITEM_ANIME_PARCHMENT,
    PIXEL_ART_ITEM_ANIME_STEINS_GATE_COMPUTERS,
    PIXEL_ART_ITEM_ANIME_STEINS_GATE_MICROWAVE,
    PIXEL_ART_ITEM_ARCADE,
    PIXEL_ART_ITEM_BOOK_UNIVERSITY,
    PIXEL_ART_ITEM_BOOK,
    PIXEL_ART_ITEM_BOOKS,
    PIXEL_ART_ITEM_CUP_COFFEE_ANIMATION,
    PIXEL_ART_ITEM_DESK_ANIMATION,
    PIXEL_ART_ITEM_DESK_INVERT_ANIMATION,
    PIXEL_ART_ITEM_DOMO_ANIMATION,
    PIXEL_ART_ITEM_DOMO,
    PIXEL_ART_ITEM_HOURGLASS,
    PIXEL_ART_ITEM_LAMP,
    PIXEL_ART_ITEM_MORTARBOARD,
    PIXEL_ART_ITEM_PENCIL_BLUE,
    PIXEL_ART_ITEM_PENCIL_PINK,
    PIXEL_ART_ITEM_PENCIL_RED,
    PIXEL_ART_ITEM_PENCIL_YELLOW,
    PIXEL_ART_ITEM_PUMP_GAME_LOGO,
    PIXEL_ART_ITEM_PUMP_STEP_BLUE_ANIMATION,
    PIXEL_ART_ITEM_PUMP_STEP_BLUE,
    PIXEL_ART_ITEM_PUMP_STEP_CENTER_ANIMATION,
    PIXEL_ART_ITEM_PUMP_STEP_CENTER,
    PIXEL_ART_ITEM_PUMP_STEP_RED_ANIMATION,
    PIXEL_ART_ITEM_PUMP_STEP_RED,
    PIXEL_ART_ITEM_SOCCER_BALL,
    PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT_V2,
    PIXEL_ART_ITEM_SPEECH_BUBBLE_BIT,
    PIXEL_ART_ITEM_STICKY_NOTE_GROUP,
    PIXEL_ART_ITEM_STICKY_NOTE,
    PIXEL_ART_ITEM_WHITEBOARD,

    PIXEL_ART_ANIME_ADVENTURE_TIME_BMO_ANIMATION,
    PIXEL_ART_ANIME_ADVENTURE_TIME_FINN_THE_HUMAN_ANIMATION,
    PIXEL_ART_ANIME_ADVENTURE_TIME_JAKE_THE_DOG_ANIMATION,
    PIXEL_ART_ANIME_ADVENTURE_TIME_MARCELINE_ANIMATION,
    PIXEL_ART_ANIME_BOKU_NO_HERO_TODOROKI_ANIMATION,
    PIXEL_ART_ANIME_KIMETSU_NO_YAIBA_KANAO,
    PIXEL_ART_ANIME_KOMI_SAN_WA_KOMYUSHOU_DESU_KOMI,
    PIXEL_ART_ANIME_MINIDEV_V1_ANIMATION,
    PIXEL_ART_ANIME_MINIDEV_V2_ANIMATION,
    PIXEL_ART_ANIME_MINIDEV_V3_ANIMATION,
    PIXEL_ART_ANIME_MINIDEV_V4_ANIMATION,
    PIXEL_ART_ANIME_MINIDEV_V5_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_ICHIKA_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_ICHIKA_CARD_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_ITSUKI_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_ITSUKI_CARD_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_MIKU_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_MIKU_CARD_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_NINO_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_NINO_CARD_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_YOTSUBA_ANIMATION,
    PIXEL_ART_ANIME_NAKANO_YOTSUBA_CARD_ANIMATION,
    PIXEL_ART_ANIME_NARUTO_HINATA_ANIMATION,
    PIXEL_ART_ANIME_STEINS_GATE_KURISU_ANIMATION,
    PIXEL_ART_ANIME_STEINS_GATE_RINTARO_ANIMATION,
    PIXEL_ART_ANIME_UMI_ANIMATION
};
